name: dual_tone_text_codespark
description: "A Flutter package to render text with sharp dual-tone color splits—vertical, horizontal, or radial. Great for stylish titles and headers."
version: 0.0.2
homepage: "https://github.com/Katayath-Sai-Kiran/dual_tone_text_codespark"

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

assets: 
  - 'assets/screenshots'

screenshots:

  screenshots:
  - path: assets/screenshots/300x650-01.png
    description: Clean horizontal dual-tone text — perfect for headlines and branding.
  - path: assets/screenshots/300x650-02.png
    description: Vertical color separation for bold UI elements and section labels.
  - path: assets/screenshots/300x650-03.png
    description: Radial split with solid center and colored outer ring for a dramatic focus.


  
topics:
  - text
  - shader
  - custom-text
  - typography
  - dual-tone

 
